name = "process-mining-worker"
main = "src/index.js"
compatibility_date = "2024-09-01"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "logs"

[env.preview]
name = "process-mining-worker-preview"

[[env.preview.r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "logs-preview"
