name = "process-mining-worker"
main = "src/index.js"
compatibility_date = "2024-09-01"

[env.preview]
name = "process-mining-worker-preview"

[placement]
mode = "smart"

[env.production.vars]
LOGS_BUCKET = "logs"

[env.preview.vars]
LOGS_BUCKET = "logs-preview"
